[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_world_example = "BiHSo6R3efRTpzJKWNSjiUvG6ucS3kiQeZzm4NZ37WdP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/masred/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
